### ISSUE TITLE
can't use includeQueryParams option

### ISSUE THREAD

**Issue by thosil** [Zooz/prometheus-api-metrics#26]
Hi,
first of all thanks for the great job you're doing here!

I'm trying to use the option "includeQueyParams" with Express, but I just get 404 errors.
I'm wondering if I'm missing something.
Here's the part where I put the middelware:
```
  app.set('views', VIEWS_DIR);
  app.set('view engine', 'pug');
  app.use(apiMetrics({
    defaultMetricsInterval: 1000,
    includeQueryParams: true,
  }));
  app.use(json());
  app.use(cors());
  app.use(breadcrumb());
  app.use(Static(path.join(__dirname, '../../public')));
```
After that part I define the routers I'm using in the rest of the app.

If I curl on "/metrics" everything is fine, but I receive a 404 when I'm trying to get "/metrics?" or "/metrics?collector[]=nodejs" etc.

Do you have any advises to make it working?

Thanks

**Comment by idanto** [comment]
Hi @thosil 

I think you a bit misunderstood this option.
The `includeQueryParams` indicate if you would like the package to collect as part of the route the query parameters.
For example, if you have a route `/pets` and you can call it with a query parameters lets say `type` and `color`.
If `includeQueryParams` if `false` both calls for `/path?type=Mammals` and `/path?color=brown` will log under the route `/path` by the package.
if `includeQueryParams` if `true` you should expect to see `/path?type=?` and `/path?color=?` as two different routes in your `/metrics` endpoint.

I hope it is more clear now.

**Comment by thosil** [comment]
Hi @idanto 
I was  understanding this in a very wrong way :sweat_smile:
Thank you for the clarifications.
