### ISSUE TITLE
collector.init is not a function

### ISSUE THREAD

**Issue by Fi1osof** [Zooz/prometheus-api-metrics#35]
import apiMetrics from 'prometheus-api-metrics';
const HttpMetricsCollector = apiMetrics.HttpMetricsCollector;
const collector = new HttpMetricsCollector();

// Here error
collector.init();

**Comment by kobik** [comment]
Hi @Fi1osof , is this still relevant?

**Comment by Fi1osof** [comment]
Hi @kobik.
Can not confirm. Used this many time ago.

**Comment by cocuba** [comment]
> import apiMetrics from 'prometheus-api-metrics';
> const HttpMetricsCollector = apiMetrics.HttpMetricsCollector;
> const collector = new HttpMetricsCollector();
> 
> // Here error
> collector.init();

it happens to me
"prometheus-api-metrics": "3.1.0",
