### ISSUE TITLE
HttpMetricsCollector should also work with axios

### ISSUE THREAD

**Issue by kaplanan** [Zooz/prometheus-api-metrics#50]
`HttpMetricsCollector._collectHttpTiming()` should also work with solutions other than the `request` library.

Currently, the method is tightly coupled to the metrics which are delivered from the request-package, however, as of Feb 2020, the request library is fully deprecated.

This would help us and many others a lot.

Thanks!
A.K.

**Comment by kobik** [comment]
Hi @kaplanan , Does this  covers you issue?

https://github.com/PayU/prometheus-api-metrics/commit/5ceb5e79877f5ef83b5d32bb19191e65cd1f4c34

**Comment by kaplanan** [comment]
Hello @kobik 
The provided solution fits perfectly. Thanks alot!
