### ISSUE TITLE
Storing the logs

### ISSUE THREAD

**Issue by nidhinprathap** [Zooz/prometheus-api-metrics#7]
Once the server crashes or restarted all the logs are gone. How can i retain the data even on restart? Is there any option of storing the data in separate DB

**Comment by idanto** [comment]
The seperte DB you supposed to use with this package is [Prometheus](https://prometheus.io) which is a time series db designed to collect, aggregate and query metrics. It has two different way to collect data push and pull. This package assume you configure prometheus to pull data from the /metrics endpoint every few seconds (the default is 10) so in the worst case you lost one scraping interval in case the service crashed.

You can use the prometheus push gateway but it had it's own drawbacks you can Google it.

**Comment by nidhinprathap** [comment]
cool. I totally missed that. I already have a Prometheus setup. I can directly connect these metrics there. How about getting only the metrics of a particular route with a pattern. Let's say all the metrics for the requests with API prefixed.

**Comment by idanto** [comment]
In theory as it is an express middleware you can add it for specific route and not for the entire app this should work for you.

We can add a parameter which will indicate which route to collect but I don't see it as a critical feature from two reasons you can overcome this as I explained and you can filter it out while you query prometheus. 

I don't mind to approve a PR for this feature.

**Comment by idanto** [comment]
In a second thought the /metrics endpoint might not work as expected in the solution I suggested so you can expose it yourself or just submit a pull request and I will review it

**Comment by idanto** [comment]
Hi @nidhinprathap, in the last version I added a feature to exclude specific routes from being collected.

Is that answering your request? I would like to close this issue.

**Comment by nidhinprathap** [comment]
yes thanks

**Comment by nidhinprathap** [comment]
will try it out

**Comment by nidhinprathap** [comment]
Do yiu have the docs for it

**Comment by idanto** [comment]
@nidhinprathap it is in the README.
here is a snippet of how to use it:
```js
app.use(metrics({ excludeRoutes: ['/health'] }));
```

**Comment by idanto** [comment]
Hi @nidhinprathap, Do you have any updates? does this helped you?
