### ISSUE TITLE
Development still active?

### ISSUE THREAD

**Issue by kdhira** [Zooz/prometheus-api-metrics#72]
Hi

I am trying to evaluate the fitness of this library in a project I am developing (to which we would be using the Koa Middleware this produces). I see that issues such as #59 also affects me usage of the middleware, but no development has been done to date and wondering if this repository is still being actively developed/maintained for any of: new features, bug fixes, security vulnerability patches etc?

**Comment by kobik** [comment]
Hi @kdhira, thanks for your interest in the package.
We're mostly maintaining the package and trying to keep it up-to-date.

Regardin #59, I'll have a look at it tomorrow and evaluate its priority.

Just a reminder, PRs are always welcome.

**Comment by proffalken** [comment]
It would be nice if we can get a bump to the latest version of prom-client at the same time if possible!

I've got enough knowledge to update the Package.json file, but not enough to ensure that all the various parts of the api-metrics side of things works properly!

**Comment by kdhira** [comment]
I have created a pull request #73 which covers the fix for my (Strapi) usecase. Please review. I also saw some `npm audit` things that might need be addressed and regressed.

Regarding the prom-client version updates, I agree that would be good, but also don't know enough to ensure there are no regressions - so collaboration on this from the maintainers would be appreciated if we want this also

**Comment by kdhira** [comment]
Thanks @kobik for reviewing and accepting my contribution :)

**Comment by kobik** [comment]
Actually, thank you for contributing :-)
